-- SAIT Medical Clinic - Advanced Database Activity 2

DROP SCHEMA IF EXISTS sait_medical_clinic CASCADE;
CREATE SCHEMA sait_medical_clinic;
SET search_path TO sait_medical_clinic;

-- Domain types used to enforce valid status/payment values
CREATE TYPE appointment_status AS ENUM ('Scheduled','Kept','Cancelled');
CREATE TYPE bill_status AS ENUM ('Paid','Outstanding');
CREATE TYPE payment_method AS ENUM ('Credit Card','Debit Card','Cash','Health Benefits');

CREATE TABLE patient (
    patient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    date_of_birth DATE NOT NULL,
    phone VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    address VARCHAR(200) NOT NULL
);

CREATE TABLE doctor (
    doctor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    specialty VARCHAR(80) NOT NULL,
    phone VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE appointment (
    appointment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL REFERENCES patient(patient_id),
    doctor_id INTEGER NOT NULL REFERENCES doctor(doctor_id),
    appointment_date DATE NOT NULL,
    appointment_time TIME NOT NULL,
    reason VARCHAR(200) NOT NULL,
    status appointment_status NOT NULL DEFAULT 'Scheduled',
    CONSTRAINT uq_doctor_datetime UNIQUE (doctor_id, appointment_date, appointment_time)
);

CREATE TABLE visit (
    visit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id INTEGER NOT NULL UNIQUE REFERENCES appointment(appointment_id),
    visit_date DATE NOT NULL,
    diagnosis VARCHAR(200) NOT NULL,
    treatment VARCHAR(300) NOT NULL,
    notes VARCHAR(500)
);

CREATE TABLE medical_history (
    history_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL REFERENCES patient(patient_id),
    visit_id INTEGER NOT NULL UNIQUE REFERENCES visit(visit_id),
    record_date DATE NOT NULL,
    summary VARCHAR(500) NOT NULL
);

CREATE TABLE bill (
    bill_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id INTEGER NOT NULL UNIQUE REFERENCES visit(visit_id),
    patient_id INTEGER NOT NULL REFERENCES patient(patient_id),
    doctor_id INTEGER NOT NULL REFERENCES doctor(doctor_id),
    amount NUMERIC(10,2) NOT NULL CHECK (amount > 0),
    bill_date DATE NOT NULL,
    status bill_status NOT NULL DEFAULT 'Outstanding',
    paid_date DATE NULL,
    payment_method payment_method NULL,
    CONSTRAINT chk_payment_details CHECK (
        (status = 'Paid' AND paid_date IS NOT NULL AND payment_method IS NOT NULL)
        OR (status = 'Outstanding' AND paid_date IS NULL AND payment_method IS NULL)
    )
);

-- --------------------
-- View requirement
-- --------------------
CREATE OR REPLACE VIEW vw_doctor_billing AS
SELECT d.doctor_id,
       CONCAT(d.first_name, ' ', d.last_name) AS doctor_name,
       d.specialty,
       COUNT(b.bill_id) AS bill_count,
       COALESCE(SUM(b.amount), 0)::NUMERIC(10,2) AS total_billed
FROM doctor d
LEFT JOIN bill b ON d.doctor_id = b.doctor_id
GROUP BY d.doctor_id, d.first_name, d.last_name, d.specialty;


-- --------------------
-- 20 patients
-- --------------------
INSERT INTO patient VALUES (1, 'Ava', 'Anderson', '1983-03-06', '403-555-1001', 'ava.anderson@example.com', '101 5 Avenue SW, Calgary, AB');
INSERT INTO patient VALUES (2, 'Liam', 'Bennett', '1986-05-11', '403-555-1002', 'liam.bennett@example.com', '102 5 Avenue SW, Calgary, AB');
INSERT INTO patient VALUES (3, 'Noah', 'Campbell', '1989-07-16', '403-555-1003', 'noah.campbell@example.com', '103 5 Avenue SW, Calgary, AB');
INSERT INTO patient VALUES (4, 'Emma', 'Davis', '1992-09-21', '403-555-1004', 'emma.davis@example.com', '104 5 Avenue SW, Calgary, AB');
INSERT INTO patient VALUES (5, 'Oliver', 'Edwards', '1995-11-26', '403-555-1005', 'oliver.edwards@example.com', '105 5 Avenue SW, Calgary, AB');
INSERT INTO patient VALUES (6, 'Mia', 'Foster', '1998-01-04', '403-555-1006', 'mia.foster@example.com', '106 5 Avenue SW, Calgary, AB');
INSERT INTO patient VALUES (7, 'Ethan', 'Garcia', '2001-03-09', '403-555-1007', 'ethan.garcia@example.com', '107 5 Avenue SW, Calgary, AB');
INSERT INTO patient VALUES (8, 'Sophia', 'Harris', '2004-05-14', '403-555-1008', 'sophia.harris@example.com', '108 5 Avenue SW, Calgary, AB');
INSERT INTO patient VALUES (9, 'Lucas', 'Irwin', '2007-07-19', '403-555-1009', 'lucas.irwin@example.com', '109 5 Avenue SW, Calgary, AB');
INSERT INTO patient VALUES (10, 'Amelia', 'Johnson', '2010-09-24', '403-555-1010', 'amelia.johnson@example.com', '110 5 Avenue SW, Calgary, AB');
INSERT INTO patient VALUES (11, 'Mason', 'King', '2013-11-02', '403-555-1011', 'mason.king@example.com', '111 5 Avenue SW, Calgary, AB');
INSERT INTO patient VALUES (12, 'Harper', 'Lewis', '1981-01-07', '403-555-1012', 'harper.lewis@example.com', '112 5 Avenue SW, Calgary, AB');
INSERT INTO patient VALUES (13, 'Logan', 'Mitchell', '1984-03-12', '403-555-1013', 'logan.mitchell@example.com', '113 5 Avenue SW, Calgary, AB');
INSERT INTO patient VALUES (14, 'Ella', 'Nelson', '1987-05-17', '403-555-1014', 'ella.nelson@example.com', '114 5 Avenue SW, Calgary, AB');
INSERT INTO patient VALUES (15, 'James', 'Parker', '1990-07-22', '403-555-1015', 'james.parker@example.com', '115 5 Avenue SW, Calgary, AB');
INSERT INTO patient VALUES (16, 'Chloe', 'Reed', '1993-09-27', '403-555-1016', 'chloe.reed@example.com', '116 5 Avenue SW, Calgary, AB');
INSERT INTO patient VALUES (17, 'Benjamin', 'Scott', '1996-11-05', '403-555-1017', 'benjamin.scott@example.com', '117 5 Avenue SW, Calgary, AB');
INSERT INTO patient VALUES (18, 'Grace', 'Turner', '1999-01-10', '403-555-1018', 'grace.turner@example.com', '118 5 Avenue SW, Calgary, AB');
INSERT INTO patient VALUES (19, 'Henry', 'Walker', '2002-03-15', '403-555-1019', 'henry.walker@example.com', '119 5 Avenue SW, Calgary, AB');
INSERT INTO patient VALUES (20, 'Nora', 'Young', '2005-05-20', '403-555-1020', 'nora.young@example.com', '120 5 Avenue SW, Calgary, AB');

-- 20 doctors
INSERT INTO doctor VALUES (1, 'Mia', 'Dr. Irwin', 'Family Medicine', '403-555-2001', 'doctor1@saitclinic.example');
INSERT INTO doctor VALUES (2, 'Ethan', 'Dr. Johnson', 'Internal Medicine', '403-555-2002', 'doctor2@saitclinic.example');
INSERT INTO doctor VALUES (3, 'Sophia', 'Dr. King', 'Pediatrics', '403-555-2003', 'doctor3@saitclinic.example');
INSERT INTO doctor VALUES (4, 'Lucas', 'Dr. Lewis', 'Cardiology', '403-555-2004', 'doctor4@saitclinic.example');
INSERT INTO doctor VALUES (5, 'Amelia', 'Dr. Mitchell', 'Dermatology', '403-555-2005', 'doctor5@saitclinic.example');
INSERT INTO doctor VALUES (6, 'Mason', 'Dr. Nelson', 'Orthopedics', '403-555-2006', 'doctor6@saitclinic.example');
INSERT INTO doctor VALUES (7, 'Harper', 'Dr. Parker', 'Neurology', '403-555-2007', 'doctor7@saitclinic.example');
INSERT INTO doctor VALUES (8, 'Logan', 'Dr. Reed', 'Endocrinology', '403-555-2008', 'doctor8@saitclinic.example');
INSERT INTO doctor VALUES (9, 'Ella', 'Dr. Scott', 'Psychiatry', '403-555-2009', 'doctor9@saitclinic.example');
INSERT INTO doctor VALUES (10, 'James', 'Dr. Turner', 'General Practice', '403-555-2010', 'doctor10@saitclinic.example');
INSERT INTO doctor VALUES (11, 'Chloe', 'Dr. Walker', 'Family Medicine', '403-555-2011', 'doctor11@saitclinic.example');
INSERT INTO doctor VALUES (12, 'Benjamin', 'Dr. Young', 'Internal Medicine', '403-555-2012', 'doctor12@saitclinic.example');
INSERT INTO doctor VALUES (13, 'Grace', 'Dr. Anderson', 'Pediatrics', '403-555-2013', 'doctor13@saitclinic.example');
INSERT INTO doctor VALUES (14, 'Henry', 'Dr. Bennett', 'Cardiology', '403-555-2014', 'doctor14@saitclinic.example');
INSERT INTO doctor VALUES (15, 'Nora', 'Dr. Campbell', 'Dermatology', '403-555-2015', 'doctor15@saitclinic.example');
INSERT INTO doctor VALUES (16, 'Ava', 'Dr. Davis', 'Orthopedics', '403-555-2016', 'doctor16@saitclinic.example');
INSERT INTO doctor VALUES (17, 'Liam', 'Dr. Edwards', 'Neurology', '403-555-2017', 'doctor17@saitclinic.example');
INSERT INTO doctor VALUES (18, 'Noah', 'Dr. Foster', 'Endocrinology', '403-555-2018', 'doctor18@saitclinic.example');
INSERT INTO doctor VALUES (19, 'Emma', 'Dr. Garcia', 'Psychiatry', '403-555-2019', 'doctor19@saitclinic.example');
INSERT INTO doctor VALUES (20, 'Oliver', 'Dr. Harris', 'General Practice', '403-555-2020', 'doctor20@saitclinic.example');

-- 32 appointments
INSERT INTO appointment VALUES (1, 7, 5, '2026-01-08', '09:00:00', 'Upper respiratory infection', 'Kept');
INSERT INTO appointment VALUES (2, 14, 10, '2026-01-19', '10:00:00', 'Hypertension', 'Kept');
INSERT INTO appointment VALUES (3, 1, 15, '2026-02-03', '11:30:00', 'Type 2 diabetes', 'Kept');
INSERT INTO appointment VALUES (4, 8, 20, '2026-02-17', '13:00:00', 'Migraine', 'Kept');
INSERT INTO appointment VALUES (5, 15, 5, '2026-03-05', '14:30:00', 'Dermatitis', 'Kept');
INSERT INTO appointment VALUES (6, 2, 10, '2026-03-23', '15:30:00', 'Lower back pain', 'Kept');
INSERT INTO appointment VALUES (7, 9, 15, '2026-04-07', '09:00:00', 'Seasonal allergies', 'Kept');
INSERT INTO appointment VALUES (8, 16, 20, '2026-04-21', '10:00:00', 'Gastritis', 'Kept');
INSERT INTO appointment VALUES (9, 3, 5, '2026-05-04', '11:30:00', 'Anxiety disorder', 'Kept');
INSERT INTO appointment VALUES (10, 10, 10, '2026-05-18', '13:00:00', 'Knee pain', 'Kept');
INSERT INTO appointment VALUES (11, 17, 15, '2026-06-02', '14:30:00', 'Asthma', 'Kept');
INSERT INTO appointment VALUES (12, 4, 20, '2026-06-15', '15:30:00', 'High cholesterol', 'Kept');
INSERT INTO appointment VALUES (13, 11, 5, '2026-06-29', '09:00:00', 'Sinusitis', 'Kept');
INSERT INTO appointment VALUES (14, 18, 10, '2026-07-07', '10:00:00', 'Insomnia', 'Kept');
INSERT INTO appointment VALUES (15, 5, 15, '2026-07-20', '11:30:00', 'Vitamin D deficiency', 'Kept');
INSERT INTO appointment VALUES (16, 12, 20, '2026-07-28', '13:00:00', 'Upper respiratory infection', 'Kept');
INSERT INTO appointment VALUES (17, 19, 5, '2026-08-03', '14:30:00', 'Hypertension', 'Kept');
INSERT INTO appointment VALUES (18, 6, 10, '2026-08-05', '15:30:00', 'Type 2 diabetes', 'Kept');
INSERT INTO appointment VALUES (19, 13, 15, '2026-08-07', '09:00:00', 'Migraine', 'Kept');
INSERT INTO appointment VALUES (20, 20, 20, '2026-08-10', '10:00:00', 'Dermatitis', 'Kept');
INSERT INTO appointment VALUES (21, 7, 5, '2026-08-12', '11:30:00', 'Lower back pain', 'Kept');
INSERT INTO appointment VALUES (22, 14, 10, '2026-08-14', '13:00:00', 'Seasonal allergies', 'Kept');
INSERT INTO appointment VALUES (23, 1, 15, '2026-08-18', '14:30:00', 'Gastritis', 'Kept');
INSERT INTO appointment VALUES (24, 8, 20, '2026-08-20', '15:30:00', 'Anxiety disorder', 'Kept');
INSERT INTO appointment VALUES (25, 15, 5, '2026-08-24', '09:00:00', 'Knee pain', 'Kept');
INSERT INTO appointment VALUES (26, 2, 10, '2026-08-26', '10:00:00', 'Asthma', 'Scheduled');
INSERT INTO appointment VALUES (27, 9, 15, '2026-08-28', '11:30:00', 'High cholesterol', 'Scheduled');
INSERT INTO appointment VALUES (28, 16, 20, '2026-09-02', '13:00:00', 'Sinusitis', 'Scheduled');
INSERT INTO appointment VALUES (29, 3, 5, '2026-09-09', '14:30:00', 'Insomnia', 'Scheduled');
INSERT INTO appointment VALUES (30, 10, 10, '2026-09-16', '15:30:00', 'Vitamin D deficiency', 'Cancelled');
INSERT INTO appointment VALUES (31, 17, 15, '2026-09-23', '09:00:00', 'Upper respiratory infection', 'Cancelled');
INSERT INTO appointment VALUES (32, 4, 20, '2026-09-29', '10:00:00', 'Hypertension', 'Cancelled');

-- 25 visits
INSERT INTO visit VALUES (1, 1, '2026-01-08', 'Migraine', 'Supportive care and follow-up', 'Follow-up recommended in 3 weeks.');
INSERT INTO visit VALUES (2, 2, '2026-01-19', 'Dermatitis', 'Medication adjustment', 'Follow-up recommended in 4 weeks.');
INSERT INTO visit VALUES (3, 3, '2026-02-03', 'Lower back pain', 'Lifestyle counselling', 'Follow-up recommended in 5 weeks.');
INSERT INTO visit VALUES (4, 4, '2026-02-17', 'Seasonal allergies', 'Prescription medication', 'Follow-up recommended in 2 weeks.');
INSERT INTO visit VALUES (5, 5, '2026-03-05', 'Gastritis', 'Physiotherapy referral', 'Follow-up recommended in 3 weeks.');
INSERT INTO visit VALUES (6, 6, '2026-03-23', 'Anxiety disorder', 'Topical treatment', 'Follow-up recommended in 4 weeks.');
INSERT INTO visit VALUES (7, 7, '2026-04-07', 'Knee pain', 'Diagnostic imaging ordered', 'Follow-up recommended in 5 weeks.');
INSERT INTO visit VALUES (8, 8, '2026-04-21', 'Asthma', 'Blood work and monitoring', 'Follow-up recommended in 2 weeks.');
INSERT INTO visit VALUES (9, 9, '2026-05-04', 'High cholesterol', 'Referral to specialist', 'Follow-up recommended in 3 weeks.');
INSERT INTO visit VALUES (10, 10, '2026-05-18', 'Sinusitis', 'Diet and exercise plan', 'Follow-up recommended in 4 weeks.');
INSERT INTO visit VALUES (11, 11, '2026-06-02', 'Insomnia', 'Supportive care and follow-up', 'Follow-up recommended in 5 weeks.');
INSERT INTO visit VALUES (12, 12, '2026-06-15', 'Vitamin D deficiency', 'Medication adjustment', 'Follow-up recommended in 2 weeks.');
INSERT INTO visit VALUES (13, 13, '2026-06-29', 'Upper respiratory infection', 'Lifestyle counselling', 'Follow-up recommended in 3 weeks.');
INSERT INTO visit VALUES (14, 14, '2026-07-07', 'Hypertension', 'Prescription medication', 'Follow-up recommended in 4 weeks.');
INSERT INTO visit VALUES (15, 15, '2026-07-20', 'Type 2 diabetes', 'Physiotherapy referral', 'Follow-up recommended in 5 weeks.');
INSERT INTO visit VALUES (16, 16, '2026-07-28', 'Migraine', 'Topical treatment', 'Follow-up recommended in 2 weeks.');
INSERT INTO visit VALUES (17, 17, '2026-08-03', 'Dermatitis', 'Diagnostic imaging ordered', 'Follow-up recommended in 3 weeks.');
INSERT INTO visit VALUES (18, 18, '2026-08-05', 'Lower back pain', 'Blood work and monitoring', 'Follow-up recommended in 4 weeks.');
INSERT INTO visit VALUES (19, 19, '2026-08-07', 'Seasonal allergies', 'Referral to specialist', 'Follow-up recommended in 5 weeks.');
INSERT INTO visit VALUES (20, 20, '2026-08-10', 'Gastritis', 'Diet and exercise plan', 'Follow-up recommended in 2 weeks.');
INSERT INTO visit VALUES (21, 21, '2026-08-12', 'Anxiety disorder', 'Supportive care and follow-up', 'Follow-up recommended in 3 weeks.');
INSERT INTO visit VALUES (22, 22, '2026-08-14', 'Knee pain', 'Medication adjustment', 'Follow-up recommended in 4 weeks.');
INSERT INTO visit VALUES (23, 23, '2026-08-18', 'Asthma', 'Lifestyle counselling', 'Follow-up recommended in 5 weeks.');
INSERT INTO visit VALUES (24, 24, '2026-08-20', 'High cholesterol', 'Prescription medication', 'Follow-up recommended in 2 weeks.');
INSERT INTO visit VALUES (25, 25, '2026-08-24', 'Sinusitis', 'Physiotherapy referral', 'Follow-up recommended in 3 weeks.');

-- 25 medical history records
INSERT INTO medical_history VALUES (1, 7, 1, '2026-01-08', 'Migraine; Supportive care and follow-up.');
INSERT INTO medical_history VALUES (2, 14, 2, '2026-01-19', 'Dermatitis; Medication adjustment.');
INSERT INTO medical_history VALUES (3, 1, 3, '2026-02-03', 'Lower back pain; Lifestyle counselling.');
INSERT INTO medical_history VALUES (4, 8, 4, '2026-02-17', 'Seasonal allergies; Prescription medication.');
INSERT INTO medical_history VALUES (5, 15, 5, '2026-03-05', 'Gastritis; Physiotherapy referral.');
INSERT INTO medical_history VALUES (6, 2, 6, '2026-03-23', 'Anxiety disorder; Topical treatment.');
INSERT INTO medical_history VALUES (7, 9, 7, '2026-04-07', 'Knee pain; Diagnostic imaging ordered.');
INSERT INTO medical_history VALUES (8, 16, 8, '2026-04-21', 'Asthma; Blood work and monitoring.');
INSERT INTO medical_history VALUES (9, 3, 9, '2026-05-04', 'High cholesterol; Referral to specialist.');
INSERT INTO medical_history VALUES (10, 10, 10, '2026-05-18', 'Sinusitis; Diet and exercise plan.');
INSERT INTO medical_history VALUES (11, 17, 11, '2026-06-02', 'Insomnia; Supportive care and follow-up.');
INSERT INTO medical_history VALUES (12, 4, 12, '2026-06-15', 'Vitamin D deficiency; Medication adjustment.');
INSERT INTO medical_history VALUES (13, 11, 13, '2026-06-29', 'Upper respiratory infection; Lifestyle counselling.');
INSERT INTO medical_history VALUES (14, 18, 14, '2026-07-07', 'Hypertension; Prescription medication.');
INSERT INTO medical_history VALUES (15, 5, 15, '2026-07-20', 'Type 2 diabetes; Physiotherapy referral.');
INSERT INTO medical_history VALUES (16, 12, 16, '2026-07-28', 'Migraine; Topical treatment.');
INSERT INTO medical_history VALUES (17, 19, 17, '2026-08-03', 'Dermatitis; Diagnostic imaging ordered.');
INSERT INTO medical_history VALUES (18, 6, 18, '2026-08-05', 'Lower back pain; Blood work and monitoring.');
INSERT INTO medical_history VALUES (19, 13, 19, '2026-08-07', 'Seasonal allergies; Referral to specialist.');
INSERT INTO medical_history VALUES (20, 20, 20, '2026-08-10', 'Gastritis; Diet and exercise plan.');
INSERT INTO medical_history VALUES (21, 7, 21, '2026-08-12', 'Anxiety disorder; Supportive care and follow-up.');
INSERT INTO medical_history VALUES (22, 14, 22, '2026-08-14', 'Knee pain; Medication adjustment.');
INSERT INTO medical_history VALUES (23, 1, 23, '2026-08-18', 'Asthma; Lifestyle counselling.');
INSERT INTO medical_history VALUES (24, 8, 24, '2026-08-20', 'High cholesterol; Prescription medication.');
INSERT INTO medical_history VALUES (25, 15, 25, '2026-08-24', 'Sinusitis; Physiotherapy referral.');

-- 25 bills
INSERT INTO bill VALUES (1, 1, 7, 5, 125.00, '2026-01-08', 'Paid', '2026-01-10', 'Credit Card');
INSERT INTO bill VALUES (2, 2, 14, 10, 175.00, '2026-01-19', 'Paid', '2026-01-22', 'Debit Card');
INSERT INTO bill VALUES (3, 3, 1, 15, 250.00, '2026-02-03', 'Paid', '2026-02-07', 'Cash');
INSERT INTO bill VALUES (4, 4, 8, 20, 110.00, '2026-02-17', 'Paid', '2026-02-22', 'Health Benefits');
INSERT INTO bill VALUES (5, 5, 15, 5, 160.00, '2026-03-05', 'Paid', '2026-03-06', 'Credit Card');
INSERT INTO bill VALUES (6, 6, 2, 10, 225.00, '2026-03-23', 'Outstanding', NULL, NULL);
INSERT INTO bill VALUES (7, 7, 9, 15, 170.00, '2026-04-07', 'Paid', '2026-04-10', 'Cash');
INSERT INTO bill VALUES (8, 8, 16, 20, 140.00, '2026-04-21', 'Paid', '2026-04-25', 'Health Benefits');
INSERT INTO bill VALUES (9, 9, 3, 5, 190.00, '2026-05-04', 'Paid', '2026-05-09', 'Credit Card');
INSERT INTO bill VALUES (10, 10, 10, 10, 85.00, '2026-05-18', 'Paid', '2026-05-19', 'Debit Card');
INSERT INTO bill VALUES (11, 11, 17, 15, 125.00, '2026-06-02', 'Paid', '2026-06-04', 'Cash');
INSERT INTO bill VALUES (12, 12, 4, 20, 175.00, '2026-06-15', 'Outstanding', NULL, NULL);
INSERT INTO bill VALUES (13, 13, 11, 5, 250.00, '2026-06-29', 'Paid', '2026-07-03', 'Credit Card');
INSERT INTO bill VALUES (14, 14, 18, 10, 185.00, '2026-07-07', 'Paid', '2026-07-12', 'Debit Card');
INSERT INTO bill VALUES (15, 15, 5, 15, 160.00, '2026-07-20', 'Paid', '2026-07-21', 'Cash');
INSERT INTO bill VALUES (16, 16, 12, 20, 225.00, '2026-07-28', 'Paid', '2026-07-30', 'Health Benefits');
INSERT INTO bill VALUES (17, 17, 19, 5, 95.00, '2026-08-03', 'Paid', '2026-08-06', 'Credit Card');
INSERT INTO bill VALUES (18, 18, 6, 10, 140.00, '2026-08-05', 'Outstanding', NULL, NULL);
INSERT INTO bill VALUES (19, 19, 13, 15, 190.00, '2026-08-07', 'Paid', '2026-08-12', 'Cash');
INSERT INTO bill VALUES (20, 20, 20, 20, 85.00, '2026-08-10', 'Paid', '2026-08-11', 'Health Benefits');
INSERT INTO bill VALUES (21, 21, 7, 5, 200.00, '2026-08-12', 'Paid', '2026-08-14', 'Credit Card');
INSERT INTO bill VALUES (22, 22, 14, 10, 175.00, '2026-08-14', 'Paid', '2026-08-17', 'Debit Card');
INSERT INTO bill VALUES (23, 23, 1, 15, 250.00, '2026-08-18', 'Paid', '2026-08-22', 'Cash');
INSERT INTO bill VALUES (24, 24, 8, 20, 110.00, '2026-08-20', 'Outstanding', NULL, NULL);
INSERT INTO bill VALUES (25, 25, 15, 5, 160.00, '2026-08-24', 'Paid', '2026-08-25', 'Credit Card');






